In [1]:
import pymcel as pc
import matplotlib.pyplot as plt
import numpy as np
from astropy.time import Time
from scipy.optimize import newton

Bienvenido a PyMCel v0.9.17 ¡al infinito y más allá!


In [2]:
deg = np.pi/180

e =0.1911663355386932 	
a =0.9223803173917017 * pc.constantes.au	
q =0.7460522521429133 * pc.constantes.au
i =3.340958441017069 * deg
node =203.8996515621043 * deg
peri =126.6728325163065 * deg
M = 312.8054663584516 * deg
tp = 2461042.918242006079 * 86400

In [3]:
mu = pc.constantes.mu_sun
h = np.sqrt(mu * a * (1 - e**2))
b = a * np.sqrt(1 - e**2)

t = Time('2029-04-13 18:52:00', scale='tdb').jd * 86400
print(t)


212737560720.0


In [4]:
def Kep1er(E):
    func = E - e * np.sin(E) - h/(a*b)*(t-tp)
    return func

In [5]:
newton(Kep1er, M)

np.float64(23.08159401493784)

In [7]:
n = h/(a*b)
M = n * (t - tp)

E = M + e * np.sin(M)
E = M + e * np.sin(M) + e**2/2 * np.sin(2*M)
print(E)

23.07976142540877


In [11]:
pc.kepler_newton(M,e,delta=1e-15)

(np.float64(23.081594014937842), np.float64(0.0), 6)

In [12]:
f = 2 * np.arctan(np.sqrt((1+e)/(1-e)) * np.tan(E/2))
print(f)

-2.216242950307876


In [13]:
p = a*(1-e**2)
r = p/(1+e*np.cos(f))
xf = r * np.cos(f)
yf = r * np.sin(f)
zf = 0
print(xf,yf,zf)

-90364515258.1854 -119998934643.5342 0


In [14]:
import spiceypy as spy
R = spy.eul2m(-node, -i, -peri, 3, 1, 3)

r = R @ np.array([xf, yf, zf])
r

array([-1.37663071e+11, -6.01196013e+10, -4.71415945e+07])

In [15]:
tabla, jd, X = pc.consulta_horizons(id='Apophis', location='@SSB', epochs='2029-04-13 18:52:00')
X[:3]

c:\Users\jaide\OneDrive\Documentos\Visual_Projects\MecCel-20261\meccelenv312\Lib\site-packages\erfa\core.py:133: ErfaWarning: ERFA function "dtf2d" yielded 1 of "dubious year (Note 6)"
  warn(f'ERFA function "{func_name}" yielded {wmsg}', ErfaWarning)


array([-1.37263651e+11, -6.04834602e+10, -4.52634041e+06])

In [17]:
#Rutinas de spyceypy

#Determinacion de orbitas
#spy.oscelt

#Determinacion de estado
#spy.conics

#Formalismo f y g para la determinacion del vector estado
#spy.prop2b

spy.conics?

Signature: spy.conics(elts: numpy.ndarray, et: float) -> numpy.ndarray
Docstring:
Determine the state (position, velocity) of an orbiting body
from a set of elliptic, hyperbolic, or parabolic orbital
elements.

https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_docs_N0067/C/cspice/conics_c.html

:param elts: Conic elements, units are km, rad, rad/sec, km**3/sec**2.
:param et: Input time in ephemeris seconds J2000.
:return: State of orbiting body at et (x, y, z, dx/dt, dy/dt, dz/dt).
File:      c:\users\jaide\onedrive\documentos\visual_projects\meccel-20261\meccelenv312\lib\site-packages\spiceypy\spiceypy.py
Type:      function

In [18]:
spy.conics([q,e, i, node, peri, M, tp, mu], t)

array([-9.34271501e+10,  1.30555013e+11, -9.17751835e+09, -2.27345265e+04,
       -1.31133413e+04,  1.62193263e+02])